# Generated by Django 3.2 on 2021-08-14 20:11

import customUser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=11, unique=True, validators=[customUser.models.validate_number], verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email address')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fullname')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Signup date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Account is active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Account is deleted')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Account is admin')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Account is staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Account is superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
