# Generated by Django 3.2 on 2021-08-15 08:01

import accounts.models_utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='profiles/no_profile.png', upload_to=accounts.models_utils.profile_directory_path, verbose_name='Profile Picture')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biography')),
                ('company', models.TextField(blank=True, max_length=500, verbose_name='Company')),
                ('website', models.URLField(blank=True, verbose_name='Company website')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
