# Generated by Django 3.2 on 2021-08-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(max_length=255, verbose_name='Delivery_name')),
                ('delivery_name_en', models.CharField(max_length=255, null=True, verbose_name='Delivery_name')),
                ('delivery_name_fa', models.CharField(max_length=255, null=True, verbose_name='Delivery_name')),
                ('delivery_name_ar', models.CharField(max_length=255, null=True, verbose_name='Delivery_name')),
                ('delivery_price', models.DecimalField(decimal_places=0, error_messages={'name': {'max_length': 'The price must be between 0 and 999,999.00'}}, help_text='Maximum 999,999.00', max_digits=6, verbose_name='Delivery price')),
                ('delivery_method', models.CharField(choices=[('IS', 'In Store'), ('HD', 'Home Delivery'), ('DD', 'Digital Delivery')], help_text='Required', max_length=255, verbose_name='Delivery method')),
                ('delivery_timeframe', models.CharField(max_length=255, verbose_name='Delivery timeframe')),
                ('delivery_timeframe_en', models.CharField(max_length=255, null=True, verbose_name='Delivery timeframe')),
                ('delivery_timeframe_fa', models.CharField(max_length=255, null=True, verbose_name='Delivery timeframe')),
                ('delivery_timeframe_ar', models.CharField(max_length=255, null=True, verbose_name='Delivery timeframe')),
                ('delivery_window', models.CharField(max_length=255, verbose_name='Delivery window')),
                ('delivery_window_en', models.CharField(max_length=255, null=True, verbose_name='Delivery window')),
                ('delivery_window_fa', models.CharField(max_length=255, null=True, verbose_name='Delivery window')),
                ('delivery_window_ar', models.CharField(max_length=255, null=True, verbose_name='Delivery window')),
                ('order', models.IntegerField(default=0, help_text='Required', verbose_name='list order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Option',
                'verbose_name_plural': 'Delivery Options',
            },
        ),
        migrations.CreateModel(
            name='PaymentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_fa', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment Selection',
                'verbose_name_plural': 'Payment Selections',
            },
        ),
    ]
