# Generated by Django 3.2 on 2021-08-14 20:11

from django.db import migrations, models
import introduction.models_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Banner title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Banner title')),
                ('title_fa', models.CharField(max_length=50, null=True, verbose_name='Banner title')),
                ('title_ar', models.CharField(max_length=50, null=True, verbose_name='Banner title')),
                ('image', models.ImageField(upload_to=introduction.models_utils.banner_directory_path, verbose_name='Image')),
                ('description', models.TextField(help_text='Banner description better not get too long ... ', max_length=400, verbose_name='Banner description')),
                ('description_en', models.TextField(help_text='Banner description better not get too long ... ', max_length=400, null=True, verbose_name='Banner description')),
                ('description_fa', models.TextField(help_text='Banner description better not get too long ... ', max_length=400, null=True, verbose_name='Banner description')),
                ('description_ar', models.TextField(help_text='Banner description better not get too long ... ', max_length=400, null=True, verbose_name='Banner description')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Benefit title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Benefit title')),
                ('title_fa', models.CharField(max_length=100, null=True, verbose_name='Benefit title')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Benefit title')),
                ('image', models.ImageField(upload_to=introduction.models_utils.benefir_directory_path, verbose_name='Image')),
                ('description', models.TextField(verbose_name='Benefit description')),
                ('description_en', models.TextField(null=True, verbose_name='Benefit description')),
                ('description_fa', models.TextField(null=True, verbose_name='Benefit description')),
                ('description_ar', models.TextField(null=True, verbose_name='Benefit description')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Fullname')),
                ('mobile', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Contact message',
                'verbose_name_plural': 'Contact messages',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Service title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Service title')),
                ('title_fa', models.CharField(max_length=100, null=True, verbose_name='Service title')),
                ('title_ar', models.CharField(max_length=100, null=True, verbose_name='Service title')),
                ('description', models.TextField(verbose_name='Service description')),
                ('description_en', models.TextField(null=True, verbose_name='Service description')),
                ('description_fa', models.TextField(null=True, verbose_name='Service description')),
                ('description_ar', models.TextField(null=True, verbose_name='Service description')),
                ('clip', models.URLField(max_length=1000, unique=True, verbose_name='Clip URL')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', introduction.models_utils.FileFieldRestricted(upload_to=introduction.models_utils.team_member_directory_path, verbose_name='Image')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('introduction_en', models.TextField(null=True, verbose_name='Introduction')),
                ('introduction_fa', models.TextField(null=True, verbose_name='Introduction')),
                ('introduction_ar', models.TextField(null=True, verbose_name='Introduction')),
                ('fullname', models.CharField(max_length=100, verbose_name='Fullname')),
                ('fullname_en', models.CharField(max_length=100, null=True, verbose_name='Fullname')),
                ('fullname_fa', models.CharField(max_length=100, null=True, verbose_name='Fullname')),
                ('fullname_ar', models.CharField(max_length=100, null=True, verbose_name='Fullname')),
                ('role', models.CharField(max_length=50, verbose_name='Role in team')),
                ('role_en', models.CharField(max_length=50, null=True, verbose_name='Role in team')),
                ('role_fa', models.CharField(max_length=50, null=True, verbose_name='Role in team')),
                ('role_ar', models.CharField(max_length=50, null=True, verbose_name='Role in team')),
                ('slug', models.SlugField(blank=True, max_length=250, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team members',
                'ordering': ('created',),
            },
        ),
    ]
