# Generated by Django 3.2 on 2021-08-15 08:00

from django.db import migrations, models
import introduction.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to=introduction.models_utils.team_member_directory_path, verbose_name='Image'),
        ),
    ]
